#!/bin/env bash

export $(grep -v '^#' $HOME/dev/config/docker-kalilinux/.env | xargs)

if ! command -v xhost &> /dev/null
then
  echo "Please install 'xhost' to run GUI app";
  exit 1;
fi

# Authorize user to control xserver
xhost +SI:localuser:$(id -un)

docker build . -t $IMAGE_NAME
docker run -tid --net host --privileged -v /hdd:/hdd --name $CONTAINER_NAME $IMAGE_NAME
docker exec -ti $CONTAINER_NAME apt install -y sudo zsh kitty curl git bat trash-cli fzf papirus-icon-theme yadm exa
docker exec -ti $CONTAINER_NAME useradd -ms /usr/bin/zsh $USER
docker exec -ti $CONTAINER_NAME gpasswd -a $USER sudo
echo "New password for root"
docker exec -ti $CONTAINER_NAME passwd root
echo "New password for ${USER}"
docker exec -ti $CONTAINER_NAME passwd $USER
# install oh my zsh
echo "installing oh my zsh"
docker exec -tiu $USER $CONTAINER_NAME sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
# setup dotconfig
echo "setup dotconfig"
docker exec -tiu $USER -w $HOME $CONTAINER_NAME yadm clone https://github.com/yudi7ll/dotfiles -f
docker exec -tiu $USER -w $HOME $CONTAINER_NAME yadm restore .
docker exec -tiu $USER -w $HOME $CONTAINER_NAME yadm bootstrap
# install packer.nvim
docker exec -tiu $USER -w $HOME $CONTAINER_NAME git clone --depth 1 https://github.com/wbthomason/packer.nvim \
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim

docker exec -tiu $USER -w $HOME $CONTAINER_NAME ln -s /hdd/Downloads .
docker exec -tiu $USER -w $HOME $CONTAINER_NAME ln -s /hdd/Documents .
docker exec -tiu $USER -w $HOME $CONTAINER_NAME ln -s /hdd/dev .
docker exec -tiu $USER -w $HOME $CONTAINER_NAME ln -s /hdd/dev/hacc/CTF .
docker exec -tiu $USER -w $HOME $CONTAINER_NAME ln -s /hdd/dev/web .

echo "commits docker image..."
docker commit $CONTAINER_NAME $IMAGE_NAME
echo "restarting container..."
docker stop $CONTAINER_NAME && docker container rm $CONTAINER_NAME
echo "done."
