#!/bin/env bash

export $(grep -v '^#' .env | xargs)

if ! command -v docker &> /dev/null
then 
  echo "'docker' command not found"
  exit 1;
fi

if ! command -v xhost &> /dev/null
then
  echo "Please install 'xhost' to run GUI app";
  exit 1;
fi

if [ -z ${CONTAINER_NAME} ]
then
  echo "CONTAINER_NAME environment variable is not defined";
  exit 1;
fi

if [ -z ${IMAGE_NAME} ]
then
  echo "IMAGE_NAME environment variable is not defined";
  exit 1;
fi

if [ -z ${USER} ]
then
  echo "USER environment variable is not defined";
  exit 1;
fi

# Authorize user to control xserver
xhost +SI:localuser:$(id -un)

docker build . -t $IMAGE_NAME
docker run -tid --net host --privileged --name $CONTAINER_NAME $IMAGE_NAME
docker exec -ti $CONTAINER_NAME apt install -y sudo zsh kitty curl git bat trash-cli fzf papirus-icon-theme yadm exa dialog
docker exec -ti $CONTAINER_NAME useradd -ms /usr/bin/zsh $USER
docker exec -ti $CONTAINER_NAME gpasswd -a $USER sudo
echo "type the new password for root :"
docker exec -ti $CONTAINER_NAME passwd root
echo "type the new password for ${USER} :"
docker exec -ti $CONTAINER_NAME passwd $USER
echo "installing oh my zsh"
docker exec -tiu $USER $CONTAINER_NAME sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
echo "setup dotconfig"
docker exec -tiu $USER -w $HOME $CONTAINER_NAME yadm clone https://github.com/yudi7ll/dotfiles -f
docker exec -tiu $USER -w $HOME $CONTAINER_NAME yadm restore .
docker exec -tiu $USER -w $HOME $CONTAINER_NAME yadm bootstrap
docker exec -tiu $USER -w $HOME $CONTAINER_NAME git clone --depth 1 https://github.com/wbthomason/packer.nvim \
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim

echo "commits docker image..."
docker commit $CONTAINER_NAME $IMAGE_NAME
echo "restarting container..."
docker stop $CONTAINER_NAME && docker container rm $CONTAINER_NAME
echo "done."
